apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfhru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yfhru
  template:
    metadata:
      labels:
        app: yfhru
    spec:
      containers:
      - image: okteto.dev/yfhru:latest
        name: yfhru
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "357368ab-0a7a-424b-ae5e-a5fe2ac7f328"
        - name: Vless_Path
          value: "/ehuiiuerpwe"
        - name: Vmess_UUID
          value: "357368ab-0a7a-424b-ae5e-a5fe2ac7f328"
        - name: Vmess_Path
          value: "/freoimbnj"
        - name: Share_Path
          value: "/v2link"
